# Generated by Django 5.1 on 2024-08-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_permission_alter_user_groups_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Manager', 'Manager'), ('Analyst', 'Analyst')], max_length=50),
        ),
    ]
